[simulation]
target_generation = 100
steps_per_second = 10
runs = 0

[population]
dim = 100
size = 10

[population.cod]
type = "Real"
args = { range = [0, 1] }

[selection]
elitism = 1
crossover_prob = 0
mutation_prob = 0.05
