[simulation]
target_generation = 0
steps_per_second = 1_000
runs = 1

[population]
dim = 1024
size = 50

[population.cod]
type = "Perm"

[selection]
elitism = 1
crossover_prob = 0.8
mutation_prob = 0.0001
