[simulation]
target_generation = 1000
steps_per_second = 1_000
runs = 10

[population]
dim = 32
size = 30

[population.cod]
type = "Perm"

[selection]
elitism = 1
crossover_prob = 0
mutation_prob = 0.05
