[simulation]
target_generation = 100

[population]
dim = 8
size = 10

[population.cod]
# one of ["Bool", "Int", "Perm", "Real"]
type = "Perm"
#args = { range=[1, 10] }

[selection]
elitism = 1
crossover_prob = 0.8
mutation_prob = 0
