[simulation]
target_generation = 30
steps_per_second = 5_000
runs = 10

[population]
dim = 10
size = 30

[population.cod]
type = "Bool"

[selection]
elitism = 1
crossover_prob = 1
mutation_prob = 0.05
